package com.app.entity;

public enum ErrorCode {

    // USER
    INVALID_PHONE_NUMBER,
    OTP_EXPIRED,
    INVALID_OTP,
    USER_NOT_FOUND,
    INVALID_TOKEN,

    // RESTAURANT
    RESTAURANT_NOT_FOUND,
    RESTAURANT_CLOSED,

    // MENU
    FOOD_ITEM_NOT_FOUND,
    INVALID_CATEGORY,

    // CART
    CART_EMPTY,
    INVALID_QUANTITY,

    // ORDER
    ORDER_NOT_FOUND,
    INVALID_ORDER_STATE,

    // PAYMENT
    PAYMENT_NOT_FOUND,
    PAYMENT_FAILED,
    INVALID_PAYMENT_STATE,

    // LOCATION
    LOCATION_NOT_FOUND,
    OUT_OF_DELIVERY_RANGE,
    INVALID_COORDINATES,

    // COMMON
    INTERNAL_SERVER_ERROR,
    BAD_REQUEST,
    FILE_UPLOAD_FAILED,
    INVALID_FILE_TYPE
    ,FILE_TOO_LARGE,
    INVALID_FILE
}