spring.application.name=food-app
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/ZestBot_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
jwt.secret=MySuperSecretKey123456789
jwt.expiration=86400000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

cloudinary.cloud-name=dtefbuxng
cloudinary.api-key=463138874798493
cloudinary.api-secret=v6OENAB7EcQDi96ISiNI9ISK5w4

